CREATE SEQUENCE sequence_cloth_items START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE sequence_shopping_car START WITH 1 BELONGS_TO_TABLE;

CREATE TABLE CLOTH_ITEMS(
    "ID_CLOTH_ITEM" BIGINT DEFAULT NEXT VALUE FOR sequence_cloth_items NOT NULL NULL_TO_DEFAULT SEQUENCE sequence_shopping_car,
    "CLOTH_ITEM_DESCRIPTION" VARCHAR(1024),
    "CLOTH_ITEM_DISCOUNT" DOUBLE,
    "CLOTH_ITEM_LOOKUPS" BIGINT,
    "CLOTH_ITEM_NAME" VARCHAR(60),
    "CLOTH_ITEM_PRICE" DECIMAL(19, 2)
);
ALTER TABLE CLOTH_ITEMS ADD CONSTRAINT PK_CLOTH_ITEMS PRIMARY KEY("ID_CLOTH_ITEM");

CREATE TABLE CLOTH_ITEM_IMAGE_URLS(
    "ID_CLOTH_ITEM" BIGINT NOT NULL,
    "CLOTHE_ITEM_IMAGE_URL" VARCHAR(255)
);

CREATE TABLE SHOPING_CART(
    "IDSHOPPING_CART" BIGINT DEFAULT NEXT VALUE FOR sequence_shopping_car NOT NULL NULL_TO_DEFAULT SEQUENCE sequence_shopping_car
);
ALTER TABLE SHOPING_CART ADD CONSTRAINT PK_SHOPPING_CART PRIMARY KEY("IDSHOPPING_CART");

CREATE TABLE SHOPING_CART_CLOTH_ITEMS(
    "SHOPPING_CART_IDSHOPPING_CART" BIGINT NOT NULL,
    "CLOTH_ITEMS_ID_CLOTH_ITEM" BIGINT NOT NULL
);

ALTER TABLE SHOPING_CART_CLOTH_ITEMS ADD CONSTRAINT FK_SHOPPINGCART_CLOTHITEM FOREIGN KEY("CLOTH_ITEMS_ID_CLOTH_ITEM") REFERENCES CLOTH_ITEMS("ID_CLOTH_ITEM") NOCHECK;
ALTER TABLE CLOTH_ITEM_IMAGE_URLS ADD CONSTRAINT FK_CLOTHITEMIMAGE_CLOTHITEM FOREIGN KEY("ID_CLOTH_ITEM") REFERENCES CLOTH_ITEMS("ID_CLOTH_ITEM") NOCHECK;
